postgresql:
  enabled: false

global:
  database:
    type: "external"
    # -- Disakbe SSL if you are using a database with TLS (like AWS RDS)
    # -- https://github.com/airbytehq/airbyte-platform/pull/361
    #ssl:
    #  enabled: false
    # -- The database host
    host: qovery.env.DATABASE_HOST
    # -- The database port
    port: qovery.env.DATABASE_PORT
    # -- The database name
    database: qovery.env.DATABASE_NAME
    # -- The database user
    user: qovery.env.DATABASE_USER
    # -- The database password
    password: qovery.env.DATABASE_PASSWORD

externalDatabase:
  # -- The database host
  host: qovery.env.DATABASE_HOST
  # -- The database port
  port: qovery.env.DATABASE_PORT
  # -- The database name
  database: qovery.env.DATABASE_NAME
  # -- The database user
  user: qovery.env.DATABASE_USER
  # -- The database password
  password: qovery.env.DATABASE_PASSWORD
  # -- JDBC URL
  jdbcURL: qovery.env.DATABASE_JDBC_URL

temporal:
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 768Mi
      cpu: 1000m
  extraEnv:
    - name: POSTGRES_TLS_ENABLED
      value: "false"
    - name: SQL_TLS_ENABLED
      value: "false"
    # -- Repllace the values above with the following if you are using an extrernal database with TLS (like AWS RDS)
    # -- https://github.com/airbytehq/airbyte-platform/pull/361
    #- name: POSTGRES_TLS_ENABLED
    #  value: "true"
    #- name: POSTGRES_TLS_DISABLE_HOST_VERIFICATION
    #  value: "true"
    #- name: SQL_TLS_ENABLED
    #  value: "true"
    #- name: SQL_TLS_DISABLE_HOST_VERIFICATION
    #  value: "true"

server:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi